package fr.adrackiin.hydranium.api.core;

import fr.adrackiin.hydranium.commons.Rank;

public class PermissionsManager {
    
    public void addPermissions(APPlayer player, Rank rank){
        switch(rank){
            case PLAYER:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                //player.addPermission("hydranium.api.command.options");
                break;
            case FRIEND:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.announce");
                break;
            case HOSTTEST:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.command.connected");
                player.addPermission("hydranium.api.command.vanish");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.announce");
                player.addPermission("hydranium.lobby.enteruhc");
                player.addPermission("hydranium.lobby.canbesent");
                break;
            case HOST:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.channel.staff");
                player.addPermission("hydranium.api.command.connected");
                player.addPermission("hydranium.api.command.vanish");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                player.addPermission("hydranium.api.command.ban");
                player.addPermission("hydranium.api.command.history");
                player.addPermission("hydranium.api.command.mute");
                player.addPermission("hydranium.api.command.broadcast");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.announce");
                player.addPermission("hydranium.lobby.enteruhc");
                player.addPermission("hydranium.lobby.canbesent");
                break;
            case LEADHOST:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.channel.staff");
                player.addPermission("hydranium.api.command.fly");
                player.addPermission("hydranium.api.command.kick");
                player.addPermission("hydranium.api.command.connected");
                player.addPermission("hydranium.api.command.vanish");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                player.addPermission("hydranium.api.command.ban");
                player.addPermission("hydranium.api.command.history");
                player.addPermission("hydranium.api.command.mute");
                player.addPermission("hydranium.api.command.broadcast");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.announce");
                player.addPermission("hydranium.lobby.enteruhc");
                player.addPermission("hydranium.lobby.canbesent");
                player.addPermission("hydranium.lobby.bypassenteruhc");
                break;
            case BUILDER:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.channel.staff");
                player.addPermission("hydranium.api.command.vanish");
                player.addPermission("hydranium.api.command.fly");
                player.addPermission("hydranium.api.command.connected");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.announce");
                player.addPermission("hydranium.lobby.command.build");
                break;
            case ADMIN:
                player.addPermission("hydranium.api.command.help");
                player.addPermission("hydranium.api.command.bug");
                player.addPermission("hydranium.api.command.eastereggs");
                player.addPermission("hydranium.api.chat.whitecolor");
                player.addPermission("hydranium.api.channel.staff");
                player.addPermission("hydranium.api.chat.color");
                player.addPermission("hydranium.api.command.fly");
                player.addPermission("hydranium.api.command.kick");
                player.addPermission("hydranium.api.command.connected");
                player.addPermission("hydranium.api.command.vanish");
                player.addPermission("hydranium.api.command.lag");
                player.addPermission("hydranium.api.command.lobby");
                player.addPermission("hydranium.api.command.compte");
                player.addPermission("hydranium.api.command.unban");
                player.addPermission("hydranium.api.command.unmute");
                player.addPermission("hydranium.api.command.broadcastall");
                player.addPermission("hydranium.api.command.vanishlist");
                player.addPermission("hydranium.api.command.msg");
                player.addPermission("hydranium.api.command.reply");
                player.addPermission("hydranium.api.command.ban");
                player.addPermission("hydranium.api.command.history");
                player.addPermission("hydranium.api.command.mute");
                player.addPermission("hydranium.api.command.broadcast");
                //player.addPermission("hydranium.api.command.options");
                player.addPermission("hydranium.api.msg.bypass");
                player.addPermission("hydranium.lobby.chat.whitecolor");
                player.addPermission("hydranium.lobby.chat.color");
                player.addPermission("hydranium.lobby.announce");
                player.addPermission("hydranium.lobby.enteruhc");
                player.addPermission("hydranium.lobby.canbesent");
                player.addPermission("hydranium.lobby.command.build");
                player.addPermission("hydranium.lobby.bypassenteruhc");
                player.addPermission("hydranium.api.command.permission");
                player.addPermission("hydranium.api.command.channel");
                player.addPermission("hydranium.api.command.lag.ram");
                player.addPermission("hydranium.api.command.gc");
        }
    }
}
